#!/usr/bin/env python3

import os
import click
import io
import mysql.connector as cntr
import manage

config = {
    'user' : 'root',
    'password' : 'c509ada97',
    'host' : '127.0.0.1',
    'database' : 'd_working'
}

global conn

@click.command()
@click.option('-s', '--show-todo', is_flag=True, help='show todo list', default=False)
@click.option('-o', '--show-all', is_flag=True, help='show all todo list', default=False)
@click.option('-d', '--show-done', is_flag=True, help='show done list', default=False)
@click.option('-a', '--add-todo', is_flag=True, help='add new todo', default=False)
@click.option('-e', '--edit-todo', help='edit a todo', default='')
@click.option('-k', '--kill', help='kill todo by id', default='')
@click.option('-l', '--list-topic', is_flag=True, help='list all topics', default=False)
@click.option('-c', '--create-topic', help='create a topic', default='')
@click.option('-w', '--switch-current-topic', help='switch current topic', default='')
@click.option('-t', '--add-trifles', is_flag=True, help='add trifles beyond todo', default=False)
@click.option('-r', '--show-trifles', is_flag=True, help='show trifles list', default=False)
@click.option('-p', '--add-tips', is_flag=True, help='add tips', default=False)
@click.option('-i', '--show-tips', is_flag=True, help='show tips', default=False)
def todo(show_todo, show_done, show_all, add_todo, edit_todo, kill, list_topic, create_topic, switch_current_topic, add_trifles, show_trifles, add_tips, show_tips):
    global conn
    conn = cntr.connect(**config)
    if show_todo:
        manage.show_todo(conn, show_all)
    elif show_done:
        manage.show_done(conn)
    elif add_todo:
        manage.add_todo(conn)
    elif len(edit_todo) > 0:
        manage.edit_todo(conn, edit_todo)
    elif len(kill):
        manage.kill_todo(conn, kill)
    elif list_topic:
        manage.list_topic(conn)
    elif len(create_topic) > 0:
        manage.create_topic(conn, create_topic)
    elif len(switch_current_topic):
        manage.switch_topic(conn, switch_current_topic)
    elif add_trifles:
        manage.add_trifles(conn)
    elif show_trifles:
        manage.show_trifles(conn)
    elif add_tips:
        manage.add_tips(conn)
    elif show_tips:
        manage.show_tips(conn)
    # elif len(commit) > 0:
        # manage.commit_diff_stat(conn, commit)
    # elif count:
        # manage.count_line_today(conn)






if __name__ == '__main__':
    todo()
